DROP TABLE IF EXISTS input_register;

CREATE TABLE input_register (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    CAPTOR_VERSION INTEGER NOT_NULL,
    CAPTOR_DATE TEXT NOT NULL,
    COMPUTER_DATE TEXT NOT NULL,
    TEMPERATURE REAL NOT NULL
);